version: 2
jobs:
  build:
    docker:
    - image: circle/node:10-stretch 
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: Test functions
          command: make -C functions test
      - run:
          name: Test client
          command: make -C client build test

