version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Upgrade docker"
          command: |
            curl -fsSL https://test.docker.com -o test-docker.sh
            sudo sh test-docker.sh
            docker --version
      - run:
          name: Test functions
          command: make -C functions test
      - run:
          name: Test client
          command: make -C client build test

