version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Test functions
          command: make -C functions test
      - run:
          name: Prepare arm support
          command: docker run --privileged linuxkit/binfmt:v0.6
      - run:
          name: Test client
          command: make -C client build test

