version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Test functions
          command: make -C functions test
      - run:
          name: Test client
          command: make -C client build test

