version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Test functions
          command: make -C functions test
      - run:
          name: Prepare arm support
          command: docker run --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
      - run:
          name: Test client
          command: make -C client build test

